import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WebQQ 预设工作台源码契约', () => {
  it('接入独立导航、CRUD、CodeMirror 表达式装饰和跨页证据意图', () => {
    const page = readFileSync(resolve('client/page.vue'), 'utf8')
    const sidebar = readFileSync(resolve('client/webqq-sidebar.vue'), 'utf8')
    const workspace = readFileSync(resolve('client/preset-workspace.vue'), 'utf8')
    const editor = readFileSync(resolve('client/preset-source-editor.vue'), 'utf8')
    const sourceExpressions = readFileSync(resolve('client/webqq/preset-source-expressions.ts'), 'utf8')
    const modelRequests = readFileSync(resolve('client/model-request-workspace.vue'), 'utf8')
    const trajectory = readFileSync(resolve('client/model-request-trajectory.vue'), 'utf8')
    const shell = readFileSync(resolve('client/webqq/workspace-shell.ts'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-presets.css'), 'utf8')

    expect(sidebar).toMatch(/label:\s*['"]预设['"]/) 
    expect(sidebar).toContain('IconFileCode')
    expect(page).toContain("currentView === 'presets'")
    expect(page).toContain('<PresetWorkspace')
    expect(page).toContain(':navigation-intent="presetEvidenceIntent"')
    expect(page).toContain('@read-request="readPresetRequestFromWorkspace"')
    expect(workspace).toContain("kind === 'core' ? 'ChatLuna' : 'Character'")
    expect(workspace).toContain('ChatLuna 预设')
    expect(workspace).toContain('Character')
    expect(workspace).toContain('新建预设')
    expect(workspace).toContain('重命名预设')
    expect(workspace).toContain('删除预设')
    expect(workspace).toContain('放弃未保存修改？')
    expect(workspace).toContain("requestDirtyAction('delete')")
    expect(workspace).toContain("emit('navigateEvidence', result, captureOrigin())")
    expect(workspace).not.toContain('打开模型请求证据')
    expect(workspace).toContain('预设已被其他位置修改')
    expect(workspace).toContain('v-if="showSaveStatus"')
    expect(workspace).not.toContain('formatBytes(document.size)')
    expect(workspace).not.toContain("return dirty.value ? '有未保存修改' : '已保存'")
    expect(workspace).not.toContain('webqq-preset-context-bar')
    expect(workspace).not.toContain('选择证据定位机器人')
    expect(workspace).not.toContain('当前没有活动逻辑会话')
    expect(workspace).not.toContain('群聊中有多个虚拟机器人')
    expect(workspace).not.toContain('botId: evidenceContext.value.botId')
    expect(workspace).not.toContain('conversationId: evidenceContext.value.conversationId')
    expect(shell).not.toContain('resolvePresetEvidenceBots')
    expect(shell).not.toContain('selectPresetEvidenceBot')
    expect(shell).not.toContain('selectedPresetBotId')
    expect(workspace).toContain('<SelectGroup>')
    expect(workspace).not.toContain('parseDocument')
    expect(workspace).not.toContain('YAML.parse')
    expect(workspace).toContain(':kind="document.kind"')
    expect(editor).toContain("from '@codemirror/lang-yaml'")
    expect(editor).toContain('HighlightStyle.define')
    expect(editor).toContain('syntaxHighlighting(presetHighlightStyle)')
    expect(editor).toContain('EditorView.theme')
    expect(editor).toContain('Decoration.mark')
    expect(editor).toContain('hoverTooltip')
    expect(editor).toContain("'查看模型请求'")
    expect(editor).toContain("h(Button, {")
    expect(editor).toContain("size: 'xs'")
    expect(editor).toContain("variant: 'ghost'")
    expect(editor).toContain("class: 'webqq-preset-expression-tooltip-link'")
    expect(editor).toContain('header.append(label, action)')
    expect(editor).toContain('IconExternalLink')
    expect(editor).toContain("onClick: () => emit('expressionClick'")
    expect(editor).not.toContain('EditorView.domEventHandlers')
    expect(editor).not.toContain("role: 'button'")
    expect(editor).not.toContain("tabindex: '0'")
    expect(editor).toContain('result.value')
    expect(workspace).toContain('resolvePresetExpressionObservedValue')
    expect(editor).toContain("source[sourceFrom] !== '{' || source[sourceTo - 1] !== '}'")
    expect(editor).toContain('codeMirrorOffset(source, sourceFrom)')
    expect(editor).toContain("expression.kind === 'control'")
    expect(editor).toContain('expression.clickable && expression.stableId')
    expect(editor).toContain('resolvePresetSourceExpressions')
    expect(editor).not.toContain('? expressionDecorations(props.expressions)')
    expect(editor).toContain("isUserEvent('input')")
    expect(editor).toContain('syncDocument.of(true)')
    expect(editor).toContain('setDecorations.of(expressionDecorations(value, activeExpressions))')
    expect(editor).toContain("emit('update:modelValue'")
    expect(editor).toContain('scrollSnapshot')
    expect(editor).toContain('toRaw(props.scrollTo)')
    expect(editor).toContain('captureScrollSnapshot')
    expect(editor).toContain('defineExpose')
    expect(editor).toContain('markRaw')
    expect(editor).toContain('view.dispatch({ effects: scrollTo })')
    expect(workspace).toContain('captureOrigin')
    expect(workspace).toContain('listScrollTop')
    expect(workspace).toContain('createScrollRestore')
    expect(workspace).toContain('originRestore')
    expect(workspace).toContain('markRaw')
    expect(workspace).toContain('shallowRef')
    expect(shell).toContain('shallowRef')
    expect(shell).toContain('markRaw')
    expect(page).toContain(':origin-restore="presetOriginRestore"')
    expect(shell).toContain('presetOriginRestore')
    expect(shell).toContain('returned.snapshot')
    expect(shell).toContain("workspaceController.selectView('presets')")
    expect(sourceExpressions).toContain("from '../../src/presets/source-document'")
    expect(sourceExpressions).toContain('parsePresetSourceDocument(input.kind, input.source)')
    expect(sourceExpressions).toContain('if (input.source === input.loadedSource) return input.serverExpressions')
    expect(sourceExpressions).toContain('clickable: false')
    expect(modelRequests).toContain('navigationIntent?: PresetEvidenceNavigationIntent')
    expect(modelRequests).toContain("bodyView.value = 'analysis'")
    expect(modelRequests).toContain("mode: 'request'")
    expect(modelRequests).toContain("@locate-result=\"completeNavigationIntent\"")
    expect(modelRequests).toContain('navigationIntentFailure')
    expect(trajectory).toContain('const analysisLocateRequest = computed(() => props.externalLocate ?? internalAnalysisLocateRequest.value)')
    expect(trajectory).toContain('externalLocate?: LocateRequest')
    expect(styles).toContain('.webqq-preset-expression.is-control')
    expect(styles).toContain('.webqq-preset-expression.is-value')
    expect(styles).toContain('.webqq-preset-expression-tooltip-value')
    expect(styles).toContain('.webqq-preset-expression-tooltip-header')
    expect(styles).toContain('.webqq-preset-expression-tooltip-action')
    expect(styles).toContain('.webqq-preset-expression-tooltip-link')
    expect(styles).toContain('body[data-sandbox-frosted] .webqq-preset-source-editor .cm-tooltip')
    expect(styles).toMatch(/body\[data-sandbox-frosted\] \.webqq-preset-source-editor \.cm-tooltip\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--webqq-panel\) 72%, transparent\)/s)
    expect(styles).toMatch(/body\[data-sandbox-frosted\] \.webqq-preset-source-editor \.cm-tooltip\s*\{[^}]*backdrop-filter:\s*saturate\(180%\) blur\(20px\)/s)
    expect(styles).toMatch(/\.webqq-preset-expression-tooltip-header\s*\{[^}]*justify-content:\s*space-between/s)
    expect(styles).toMatch(/\.webqq-preset-expression-tooltip-action \.webqq-preset-expression-tooltip-link\s*\{[^}]*height:\s*24px/s)
    expect(styles).toMatch(/\.webqq-preset-expression\.is-value\s*\{[^}]*text-decoration:\s*underline;[^}]*\}/s)
    expect(styles).not.toMatch(/\.webqq-preset-expression\.is-value\s*\{[^}]*cursor:/s)
    expect(styles).toContain('padding: 24px')
    expect(styles).toContain('grid-template-columns: minmax(280px, 360px) minmax(0, 1fr)')
    expect(styles).toContain('border-radius: 16px')
    expect(styles).toMatch(/\.webqq-preset-list-pane,\s*\n\s*\.webqq-preset-editor-pane\s*\{[^}]*display:\s*grid/s)
    expect(styles).toMatch(/\.webqq-preset-empty\s*\{[^}]*place-items:\s*center/s)
    expect(styles).toMatch(/\.webqq-preset-empty\.is-editor\s*\{[^}]*grid-row:\s*1 \/ -1/s)
    expect(styles).toContain('.webqq-preset-token-key')
    expect(styles).toContain('.webqq-workspace[data-color-mode="dark"] .webqq-preset-source-editor')
    expect(page).toContain(':can-return-to-preset="canReturnFromPresetEvidence"')
    expect(page).toContain('@return-to-preset="returnFromPresetEvidence"')
    expect(modelRequests).toContain('requestNavigationIntent?: ModelRequestNavigationIntent')
    expect(modelRequests).toContain('beginModelRequestListNavigation(selectionState.value, intent.recordId)')
    expect(modelRequests).toContain('v-for="record in displayRecords"')
    expect(modelRequests).toContain('resolveModelRequestListRecords(')
    expect(modelRequests).toContain("'is-selected': record.id === selectedRecordId")
    expect(modelRequests).toContain(':aria-current="record.id === selectedRecordId')
    expect(modelRequests).toContain('canReturnToPreset?: boolean')
    expect(modelRequests).toContain("returnToPreset: []")
    expect(modelRequests).toContain('canReturnToTrajectory || canReturnToPreset')
    expect(modelRequests).toContain("canReturnToTrajectory ? '返回轨迹' : '返回预设'")
    expect(modelRequests).toContain('class="webqq-model-request-return"')
    expect(modelRequests).toContain("if (canReturnToTrajectory.value) return returnToTrajectory()")
    expect(modelRequests).toContain("emit('returnToPreset')")
    expect(modelRequests.indexOf('webqq-model-request-actions')).toBeLessThan(modelRequests.indexOf('webqq-model-request-return'))
    expect(modelRequests.indexOf('webqq-model-request-return')).toBeLessThan(modelRequests.indexOf('webqq-model-request-detail-nav'))
    expect(shell).toContain('canReturnFromPresetEvidence')
    expect(shell).toContain('returnFromPresetEvidence')
    expect(shell).toContain('presetEvidenceNavigation.returnToOrigin()')
    expect(shell).toContain('clearPresetEvidenceReturn')
    expect(shell).toContain("if (currentView.value === 'model-requests') clearPresetEvidenceReturn()")
  })

  it('表达式悬停值滚动条不绘制轨道背景', () => {
    const styles = readFileSync(resolve('client/styles/webqq-presets.css'), 'utf8')
    const valueRule = styles.slice(styles.indexOf('.webqq-preset-expression-tooltip-value {')).split('}')[0]
    expect(valueRule).toContain('scrollbar-color: #94a3b8 transparent')
    const trackRule = styles
      .slice(styles.indexOf('.webqq-preset-expression-tooltip-value::-webkit-scrollbar-track {'))
      .split('}')[0]
    expect(trackRule).toContain('background: transparent')
  })
})
