import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WebQQ 消息列表', () => {
  it('从页面提取消息渲染与消息交互', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')
    const chatPaneSource = readFileSync(resolve('client/webqq-chat-pane.vue'), 'utf8')
    const scrollbarSource = readFileSync(resolve('client/webqq-scrollbar.ts'), 'utf8')
    const emojiPickerSource = readFileSync(resolve('client/webqq-emoji-picker.vue'), 'utf8')
    const forwardModalSource = readFileSync(resolve('client/webqq-forward-modal.vue'), 'utf8')
    const forwardTargetSource = readFileSync(resolve('client/webqq-forward-target-dialog.vue'), 'utf8')

    expect(source).toContain('model: WebqqMessageListModel')
    expect(source).toContain('getMessageClusterClass')
    expect(source).toContain('replyMessages: Record<string, SandboxMessage>')
    expect(source).toContain('forwardPreviews: Record<string, SandboxForwardPreview>')
    expect(source).toContain('selectionMode?: boolean')
    expect(source).toContain('enterSelection: [messageId: string]')
    expect(source).toContain('props.model.replyMessages[message.replyToMessageId]')
    expect(source).toContain('isMergedMessage')
    expect(source).toContain('class="chatluna-sandbox-message-quote is-clickable"')
    expect(source).toContain('class="chatluna-sandbox-message-quote chatluna-sandbox-message-forward"')
    expect(source).toContain('openForward: [input: { messageId: string; forwardId: string }]')
    expect(source).toContain('class="chatluna-sandbox-message-forward-entry"')
    expect(source).toContain('class="chatluna-sandbox-message-event"')
    expect(source).toContain("message.authorId === model.currentOperatorId ? 'is-outgoing' : 'is-incoming'")
    expect(source).toContain('loadHistory: [resolve: () => void')
    expect(source).toContain("!model.currentGroup && getChatFriendActions(message.authorId).includes('remark')")
    expect(source).toContain("!model.currentGroup && getChatFriendActions(message.authorId).includes('delete')")
    expect(source).toContain('ref="messagesElement"')
    expect(source).toContain('@scroll="handleMessagesScroll"')
    expect(source).toContain("from './webqq/message-list-scroll'")
    expect(source).toContain("from './webqq/message-reveal'")
    expect(source).toContain('function revealMessage(messageId: string)')
    expect(source).toContain('defineExpose({')
    expect(source).toContain('createMessageListFollowController')
    expect(source).toContain('shouldFollowMessageListTail(')
    expect(source).toContain('follow.handleScroll()')
    expect(source).toContain('follow.handleUserScrollIntent()')
    expect(source).toContain('follow.scheduleBottom')
    expect(source).toContain('new ResizeObserver')
    expect(source).toContain('contentResizeObserver?.disconnect()')
    expect(source).toContain('watch(scrollStateKey')
    expect(source).toContain('saveMessageListScrollState()')
    expect(source).toContain('restoreMessageListScrollState(nextKey)')
    expect(source).toContain("from './webqq/message-list-scroll-state'")
    expect(source).toContain('@wheel.passive="handleMessageListUserScroll"')
    expect(source).toContain('@touchstart.passive="handleMessageListUserScroll"')
    expect(source).toContain('@pointerdown="finishMessageListScrollRestore"')
    expect(source).toContain('if (!messagesElement.value || restoringScrollState) return')
    expect(source).toContain('if (restoringScrollState) scheduleMessageListScrollRestore(activeScrollStateKey)')
    expect(source).toContain('cancelAnimationFrame(restoreSettleFrame)')
    expect(source).toContain('follow.setStickingToBottom(false)')
    expect(source).toContain("from './webqq/message-list-follow'")
    expect(styles).toContain('overflow-anchor: none')
    expect(scrollbarSource).not.toContain('stickingToBottom')
    expect(scrollbarSource).not.toContain('shouldFollowMessageListTail')
    expect(scrollbarSource).toContain('showOverlay?: boolean')
    expect(scrollbarSource).toContain("visible && state.showOverlay")
    expect(emojiPickerSource).toContain("v-webqq-scrollbar=\"{ showOverlay: false, tone: 'accent', zIndex: 140 }\"")
    expect(forwardModalSource).toContain('v-webqq-scrollbar="{ showOverlay: false }"')
    expect(forwardTargetSource).toContain("v-webqq-scrollbar=\"{ showOverlay: false, tone: 'accent' }\"")
    expect(source).toContain('clearConversation: []')
    expect(source).toContain('清空会话记录')
    expect(source).toContain('<ContextMenuTrigger as-child :disabled="preview || model.selectionMode || !model.currentConversation">')
    expect(chatPaneSource).toContain('@clear-conversation="emit(\'clearConversation\')"')
    expect(source).toContain('跳转到对应请求')
    expect(source).toContain("isBotParticipant(message.authorId) && message.chatLuna?.modelRequests?.length")
    expect(source).toContain("emit('openModelRequest', message.chatLuna.modelRequests.at(-1)!)")
    expect(chatPaneSource).toContain('@open-model-request="emit(\'openModelRequest\', $event)"')
    expect(chatPaneSource).toContain('openModelRequest: [reference: SandboxMessageModelRequestReference]')
    expect(source).toContain('message.chatLuna?.modelRequests?.length')
    expect(chatPaneSource).toContain('clearConversation: []')
    expect(source).toContain('class="webqq-welcome"')
    expect(source).toContain("'is-bot': model.avatarKind === 'bot'")
    expect(source).toContain('class="webqq-welcome-status"')
    expect(source).toContain('在线 · OneBot 机器人')
    expect(source).toContain('class="webqq-welcome-divider"')
    expect(source).toContain('发送一条消息开始测试')
    expect(source).toContain('在模拟 QQ 环境中体验 OneBot 的消息交互')
    expect(source).toContain('发送消息，验证插件在模拟 QQ 环境中的响应')
    expect(source).toContain('<ol v-else ref="messagesContentElement">')
    // 消息操作菜单只能由气泡本身触发，消息行的头像、时间和外部留白不能成为触发区域。
    const messageActionMenuSource = source.slice(source.indexOf('<ContextMenu v-else>'), source.indexOf('<li\n          v-if="shouldShowThinking(message)"'))
    expect(messageActionMenuSource).toContain('<ContextMenuTrigger as-child :disabled="isRecalledMessage(message) || model.selectionMode">\n                      <div class="chatluna-sandbox-message-bubble"')
    expect(messageActionMenuSource).not.toContain('<ContextMenuTrigger as-child :disabled="isRecalledMessage(message) || model.selectionMode">\n            <li')
    expect(chatPaneSource).toContain('<WebqqMessageList')
    expect(chatPaneSource).toContain('<WebqqForwardModal')
    expect(chatPaneSource).toContain('@open-forward="openForwardDialog"')
    expect(chatPaneSource).not.toContain('class="chatluna-sandbox-messages"')
  })

  it('合并转发卡片 1:1 复刻 quote/forward 尺寸与入口文案', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')
    const modalSource = readFileSync(resolve('client/webqq-forward-modal.vue'), 'utf8')
    const overlays = readFileSync(resolve('client/styles/webqq-overlays.css'), 'utf8')

    expect(source).toContain('查看{{ getForwardPreview(message)!.total }}条转发消息')
    expect(source).toContain('getForwardPreview(message)?.title || \'合并转发\'')
    expect(styles).toContain('.chatluna-sandbox-message-quote.chatluna-sandbox-message-forward')
    expect(styles).toContain('width: 260px')
    expect(styles).toContain('.chatluna-sandbox-message-forward-entry')
    expect(styles).toContain("content: \"›\"")
    expect(styles).toContain('border-left-color: rgb(161 161 170 / 62%)')
    expect(styles).toContain('background: rgb(39 39 42 / 62%)')
    expect(styles).toContain('border-top-color: rgb(161 161 170 / 28%)')
    expect(modalSource).toContain('class="chatluna-sandbox-forward-modal-backdrop"')
    expect(modalSource).toContain('aria-label="合并转发消息"')
    expect(modalSource).toContain('@keydown.esc="emit(\'close\')"')
    expect(modalSource).toContain('IconChevronLeft')
    expect(modalSource).toContain('canNavigateBack: boolean')
    expect(modalSource).toContain("back: []")
    expect(modalSource).toContain('aria-label="返回上一层合并转发"')
    expect(modalSource).toContain('getForwardNodeClusterClass')
    expect(modalSource).toContain('class="chatluna-sandbox-message-quote chatluna-sandbox-message-forward"')
    expect(overlays).toContain('.chatluna-sandbox-forward-modal-backdrop')
    expect(overlays).toContain('z-index: 160')
    expect(overlays).toContain('width: min(480px, calc(100vw - 32px))')
    expect(overlays).toContain('max-height: min(80vh, 620px)')
    expect(overlays).toContain('padding: 14px 16px 28px')
    const forwardModalRule = overlays.slice(overlays.indexOf('.chatluna-sandbox-forward-modal {')).split('}')[0]
    const darkForwardModalRule = overlays.slice(overlays.indexOf('body[data-sandbox-color-scheme="dark"] .chatluna-sandbox-forward-modal {')).split('}')[0]
    expect(forwardModalRule).toContain('border: 1px solid transparent')
    expect(darkForwardModalRule).toContain('border-color: transparent')
    expect(darkForwardModalRule).toContain('background: rgb(44 44 48 / 98%)')
    expect(overlays).not.toContain('cursor:')
  })

  it('显式深色主题下区分其他用户与当前操作者气泡', () => {
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')
    const darkIncomingRule = styles.indexOf(
      '.webqq-workspace[data-color-mode="dark"] .chatluna-sandbox-message-bubble {\n  --webqq-bubble-bg:',
    )
    const darkOutgoingRule = styles.lastIndexOf('.webqq-workspace[data-color-mode="dark"] .chatluna-sandbox-message-row.is-outgoing .chatluna-sandbox-message-bubble')

    const darkIncomingBubble = styles.slice(darkIncomingRule, darkIncomingRule + 420)
    expect(darkIncomingBubble).toContain('--webqq-bubble-bg: rgb(57 57 63)')
    expect(darkIncomingBubble).toContain('--webqq-reaction-bg: rgb(47 47 52)')
    expect(darkIncomingBubble).toContain('border-color: rgb(113 113 122 / 36%)')
    expect(darkIncomingBubble).toContain('background: var(--webqq-bubble-bg)')

    expect(darkOutgoingRule).toBeGreaterThan(darkIncomingRule)
    const darkOutgoingBubble = styles.slice(darkOutgoingRule, darkOutgoingRule + 360)
    expect(darkOutgoingBubble).toContain('--webqq-bubble-bg: var(--webqq-accent)')
    expect(darkOutgoingBubble).toContain('background: var(--webqq-bubble-bg)')
    expect(darkOutgoingBubble).toContain('box-shadow: none')
  })

  it('按机器人参与者和逻辑会话渲染 ChatLuna 等待态', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')

    expect(source).toContain('chatLunaStates: SandboxChatLunaState[]')
    expect(source).toContain("state.botParticipantId === model.currentOperatorId ? 'is-outgoing' : 'is-incoming'")
    expect(styles).toContain('.webqq-chatluna-thinking-dots')
    expect(styles).toContain('@keyframes webqq-chatluna-thinking-dot')
  })

  it('思考指标 1:1 复用 onebot-webqq 的结构与交互', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')

    expect(source).toContain('class="chatluna-sandbox-thinking-row"')
    expect(source).toContain('getMessageThinking(message)')
    expect(source).toContain('class="chatluna-sandbox-thinking-row is-usage-only"')
    expect(source).toContain('getMessageUsage(message)')
    // 思考归档在消息上，多轮对话后每条机器人消息各自保留指标。
    expect(source).toContain('message.chatLuna?.thought')
    expect(source).toContain('<Transition name="chatluna-sandbox-thinking" @before-leave="prepareThinkingPanelLeave">')
    expect(source).toContain('class="chatluna-sandbox-thinking-content"')
    expect(source).toContain('chatluna-sandbox-thinking-usage-icon is-input')
    expect(source).toContain('chatluna-sandbox-thinking-usage-icon is-output')
    // 思考行不能复用带头像的消息行，否则会渲染成一条独立机器人消息。
    expect(source).not.toContain('chatluna-sandbox-message-row chatluna-sandbox-thinking-row')
    expect(source).toContain('v-show="state.thinking"')
    // Token 指标默认隐藏，仅在悬停或聚焦折叠按钮时淡入。
    expect(styles).toContain('.chatluna-sandbox-thinking-toggle:hover .chatluna-sandbox-thinking-usage')
    expect(styles).toContain('.chatluna-sandbox-thinking-row.is-usage-only .chatluna-sandbox-thinking-usage')
    expect(styles).toContain('.chatluna-sandbox-thinking-row .chatluna-sandbox-thinking-chevron.is-expanded')
    expect(styles).toContain('transform: rotate(90deg)')
    expect(styles).toContain('max-width: min(360px, 100%)')
    expect(styles).toContain('white-space: pre-wrap')
    expect(styles).toContain('.chatluna-sandbox-thinking-row.is-incoming')
  })

  it('机器人在左侧时 Token 镜像到右侧但箭头仍紧跟思考时长', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')
    const readRule = (selector: string) => styles.slice(styles.indexOf(`\n${selector} {`) + 1).split('}')[0]

    expect(source).toContain('class="chatluna-sandbox-thinking-duration"')
    expect(readRule('.chatluna-sandbox-thinking-row.is-incoming .chatluna-sandbox-thinking-duration')).toContain('order: 1')
    expect(readRule('.chatluna-sandbox-thinking-row.is-incoming .chatluna-sandbox-thinking-chevron')).toContain('order: 2')
    expect(readRule('.chatluna-sandbox-thinking-row.is-incoming .chatluna-sandbox-thinking-usage')).toContain('order: 3')
    // 箭头贴到行首会被误读成换行符，两侧朝向必须一致。
    expect(readRule('.chatluna-sandbox-thinking-row.is-incoming .chatluna-sandbox-thinking-toggle')).not.toContain('flex-direction')
    expect(readRule('.chatluna-sandbox-thinking-row .chatluna-sandbox-thinking-chevron.is-expanded')).toContain('transform: rotate(90deg)')
    expect(styles).not.toContain('transform: rotate(180deg)')
    // 指标行换行会把箭头挤到第二行，必须始终单行。
    expect(readRule('.chatluna-sandbox-thinking-toggle')).not.toContain('flex-wrap')
    expect(readRule('.chatluna-sandbox-thinking-toggle')).toContain('white-space: nowrap')
    expect(readRule('.chatluna-sandbox-thinking-usage')).not.toContain('flex-wrap')
    expect(readRule('.chatluna-sandbox-thinking-usage')).toContain('white-space: nowrap')
  })

  it('固定 TIM 并显示消息时间与群身份', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')

    expect(source).toContain('formatMessageTime(message.createdAt)')
    expect(source).toContain('class="chatluna-sandbox-message-time"')
    expect(source).toContain('getMessageAuthorName(message.authorId)')
    expect(source).toContain('getMessageRoleBadge(message.authorId)')
    expect(source).not.toContain('chatStyle')
    expect(styles).toContain('.chatluna-sandbox-message-time')
    expect(styles).toContain('opacity: 0')
    expect(styles).toContain('.chatluna-sandbox-message-row:hover .chatluna-sandbox-message-time')
    expect(styles).toContain('opacity: 1')
    expect(styles).toContain('.chatluna-sandbox-message-row.is-outgoing .chatluna-sandbox-message-body')
    expect(styles).toContain('flex-direction: row-reverse')
    expect(styles).toContain('.webqq-role-badge.is-owner')
    expect(styles).toContain('.webqq-role-badge.is-admin')
    expect(styles).not.toContain('data-chat-style')
  })

  it('专属头衔复用群身份徽标位置并提供设置入口', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')
    const menuSource = readFileSync(resolve('client/group-member-menu.vue'), 'utf8')
    const detailsSource = readFileSync(resolve('client/webqq-details-panel.vue'), 'utf8')
    const overlaySource = readFileSync(resolve('client/workspace-overlay-host.vue'), 'utf8')
    const pageSource = readFileSync(resolve('client/page.vue'), 'utf8')

    expect(source).toContain('getGroupAuthorityBadge')
    expect(source).toContain("emit('setGroupTitle', message.authorId)")
    // 头衔沿用同一个徽标槽位，不新增第二个徽标元素。
    expect(source).toContain('class="webqq-role-badge"')
    expect(styles).toContain('.webqq-role-badge.is-title')
    expect(menuSource).toContain("actions.includes('set-title')")
    expect(menuSource).toContain('设置专属头衔')
    expect(detailsSource).toContain('class="chatluna-sandbox-group-member-badges"')
    expect(detailsSource).toContain('<em v-if="member.title" class="is-title">')
    expect(overlaySource).toContain("title: { title: '设置专属头衔'")
    expect(pageSource).toContain("@set-group-title=\"openGroupActionDialog('title', $event)\"")
  })

  it('撤回消息按 markRecalledMessages 在原气泡与事件之间切换', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')
    const shellSource = readFileSync(resolve('client/webqq/workspace-shell.ts'), 'utf8')

    expect(source).toContain('markRecalledMessages: boolean')
    expect(source).toContain('shouldRenderAsEvent(message)')
    expect(source).toContain("{ 'is-recalled': isRecalledMessage(message) }")
    expect(source).toContain('shouldShowThinking(message)')
    expect(source).toContain('class="chatluna-sandbox-message-recalled-label">已撤回</span>')
    expect(source).toContain('v-if="!isRecalledMessage(message)" @select="emit(\'reply\', message.id)"')
    expect(source).toContain('as-child :disabled="isRecalledMessage(message) || model.selectionMode"')
    expect(source).toContain('formatRecalledMessageEventText')
    expect(source).toContain('isRecalledMessage(message)')
    // 关闭配置时隐藏原文与思考；开启时保留气泡并弱化。
    expect(source).toContain("isRecalledMessage(message) && !props.model.markRecalledMessages")
    expect(styles).toContain('.chatluna-sandbox-message-row.is-recalled')
    expect(styles).toContain('.chatluna-sandbox-message-row.is-recalled .chatluna-sandbox-message-text')
    expect(styles).toContain('text-decoration-line: line-through')
    expect(styles).toContain('.chatluna-sandbox-message-row.is-recalled .chatluna-sandbox-message-media audio')
    const mediaRecallLine = styles.slice(
      styles.indexOf('.chatluna-sandbox-message-row.is-recalled .chatluna-sandbox-message-media::after'),
      styles.indexOf('.chatluna-sandbox-message-recalled-label'),
    )
    expect(mediaRecallLine).toContain('pointer-events: none')
    expect(styles).toContain('.chatluna-sandbox-message-recalled-label')
    expect(styles).toContain('.chatluna-sandbox-thinking-row.is-recalled')
    expect(shellSource).toContain('markRecalledMessages: appearance.value.sandboxMarkRecalledMessages')
  })

  it('私聊与群聊展示表情回应，并在聊天区打开二级选择页', () => {
    const source = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')
    const reactionsSource = readFileSync(resolve('client/webqq-message-reactions.vue'), 'utf8')
    const pickerSource = readFileSync(resolve('client/webqq-emoji-picker.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-messages.css'), 'utf8')
    const chatPaneSource = readFileSync(resolve('client/webqq-chat-pane.vue'), 'utf8')
    const pageSource = readFileSync(resolve('client/page.vue'), 'utf8')

    expect(source).toContain('<WebqqMessageReactions')
    expect(source).toContain('贴表情')
    expect(source).toContain('canReactToMessage(message)')
    // 私聊与群聊都允许主动贴表情，不再依赖当前群组。
    const reactionPermissionSource = source.slice(source.indexOf('function canReactToMessage'), source.indexOf('function toggleReaction'))
    expect(reactionPermissionSource).not.toContain('props.model.currentGroup')
    expect(reactionPermissionSource).toContain('!message.event')
    expect(reactionPermissionSource).toContain('!isRecalledMessage(message)')
    expect(source).toContain("emit('openReactionPicker', message.id)")
    expect(source).toContain("emit('setMessageReaction', message.id, emojiId, enabled)")
    expect(source).toContain("getMessageGroupMemberActions(message.authorId).includes('mention')")
    expect(source).toContain("getMessageGroupMemberActions(message.authorId).includes('poke')")
    expect(source).toMatch(/<ContextMenuItem v-if="!model\.currentGroup && getChatFriendActions\(message\.authorId\)\.includes\('poke'\)" @select="emit\('pokeFriend', message\.authorId\)">/)
    expect(source).not.toContain('好友互动')
    expect(source).toContain('hasMessageGroupMemberManagementActions(message.authorId)')
    expect(source).toContain('management-only')
    expect(reactionsSource).toContain('class="chatluna-sandbox-message-reaction"')
    expect(reactionsSource).toContain('chatluna-sandbox-message-reaction-users')
    expect(reactionsSource).not.toContain('chatluna-sandbox-message-reaction-total')
    expect(reactionsSource).not.toContain("'is-mine'")
    expect(styles).not.toContain('.chatluna-sandbox-message-reaction.is-mine')
    expect(reactionsSource).toContain('MAX_VISIBLE_REACTION_AVATARS')
    expect(pickerSource).toContain('searchSandboxEmojiFaces')
    expect(pickerSource).toContain('常用')
    expect(pickerSource).toContain('搜索表情名称、拼音或 ID')
    expect(pickerSource).toContain('class="chatluna-sandbox-secondary-page chatluna-sandbox-emoji-picker-page chatluna-sandbox-solid-secondary-surface"')
    expect(pickerSource).toContain('<Teleport to="body">')
    expect(pickerSource).toContain("zIndex: 140")
    expect(pickerSource).not.toContain('<Dialog')
    expect(pickerSource).not.toContain('aria-label="返回聊天"')
    expect(styles).toContain('.chatluna-sandbox-message-reactions')
    expect(styles).toContain('min-height: unset')
    expect(styles).toContain('padding: 0 0 0 2px')
    expect(styles).toContain('.chatluna-sandbox-message-reaction-avatar:not(:only-child):not(:last-child)')
    expect(styles).toContain('padding: 1px')
    expect(pickerSource).toContain("document.addEventListener('pointerdown', closeOnOutsidePointer)")
    expect(styles).toContain('.chatluna-sandbox-message-reaction-avatar-image.is-bot')
    expect(styles).toContain('background: var(--webqq-accent)')
    expect(styles).toContain('--webqq-reaction-bg: color-mix(in srgb, var(--webqq-bubble-bg) 88%, #64748b 12%)')
    expect(styles).toContain('--webqq-reaction-bg: rgb(47 47 52)')
    expect(styles).toContain('--webqq-reaction-bg: color-mix(in srgb, var(--webqq-bubble-bg) 88%, #0f172a 12%)')
    expect(styles).not.toContain('var(--webqq-accent) 16%, #ffffff 84%')
    expect(styles).toContain('.chatluna-sandbox-emoji-picker-grid')
    expect(chatPaneSource).toContain('@open-reaction-picker="openReactionPicker"')
    expect(chatPaneSource).toContain('<WebqqEmojiPicker')
    expect(chatPaneSource).toContain("emit('setMessageReaction', messageId, emojiId, true)")
    expect(chatPaneSource).toContain("@set-message-reaction=\"forwardSetMessageReaction\"")
    expect(pageSource).toContain('@set-message-reaction="setMessageReaction"')
  })
})
