import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WebQQ 聊天区域', () => {
  it('组合顶栏、消息列表与发送控件', () => {
    const source = readFileSync(resolve('client/webqq-chat-pane.vue'), 'utf8')
    const pageSource = readFileSync(resolve('client/page.vue'), 'utf8')

    expect(source).toContain('<main class="webqq-chat"')
    expect(source).toContain('<WebqqMessageList')
    expect(source).toContain('<WebqqComposer')
    expect(source).toContain('watch(() => props.model.conversationId')
    expect(source).toContain('forwardTargets: WebqqForwardTargetModel')
    expect(source).toContain('sendForwardMessage:')
    expect(source).toContain('getForwardMessage:')
    expect(source).toContain('<WebqqForwardModal')
    expect(source).toContain('@open-forward="openForwardDialog"')
    expect(source).toContain('const forwardStack = ref<ForwardDialogFrame[]>([])')
    expect(source).toContain('const forwardDialog = computed(() => forwardStack.value.at(-1))')
    expect(source).toContain(':can-navigate-back="forwardStack.length > 1"')
    expect(source).toContain('@back="popForwardDialog"')
    expect(source).toContain("mode === 'push' ? [...forwardStack.value, frame] : [frame]")
    expect(source).toContain("openForwardByInput(input, 'replace')")
    expect(source).toContain("openForwardByInput({ forwardId }, 'push')")
    expect(source).toContain('forwardStack.value = forwardStack.value.slice(0, -1)')
    expect(source).toContain('forwardStack.value = []')
    expect(source).not.toContain('koishiWorkspacePort')
    expect(pageSource).toContain('<WebqqChatPane')
    expect(pageSource).toContain('@send-forward-message="sendForwardMessage"')
    expect(pageSource).toContain('@get-forward-message="getForwardMessage"')
    expect(pageSource).not.toContain('class="webqq-chat-header"')
  })

  it('在顶栏提供查找聊天记录并定位历史消息', () => {
    const source = readFileSync(resolve('client/webqq-chat-pane.vue'), 'utf8')
    const searchSource = readFileSync(resolve('client/webqq-message-search.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-chat.css'), 'utf8')
    const pageSource = readFileSync(resolve('client/page.vue'), 'utf8')
    const shellSource = readFileSync(resolve('client/webqq/workspace-shell.ts'), 'utf8')
    const messageListSource = readFileSync(resolve('client/webqq-message-list.vue'), 'utf8')

    expect(source).toContain('aria-label="查找聊天记录"')
    expect(source).toContain('class="webqq-chat-search-shell"')
    expect(source).toContain("'is-expanded': searchOpen")
    expect(source).toContain(':aria-expanded="searchOpen"')
    expect(source).toContain('aria-controls="webqq-message-search-results"')
    expect(source).toContain('<WebqqMessageSearch')
    expect(source.indexOf('class="webqq-chat-header-actions"')).toBeLessThan(source.indexOf('<WebqqMessageSearch'))
    expect(source.indexOf('<WebqqMessageSearch')).toBeLessThan(source.indexOf('</header>'))
    expect(source).toContain('@close="closeSearch(true)"')
    expect(source).toContain('searchTriggerRef.value?.focus()')
    expect(source).toContain('searchConversationMessages:')
    expect(source).toContain('ensureMessageLoaded(')
    expect(source).toContain('messageListRef.value?.revealMessage')
    expect(source).toContain('closeSearch()')
    expect(source).toContain('resetSearchState()')
    expect(searchSource).toContain('id="webqq-message-search-results"')
    expect(searchSource).toContain('v-if="hasQuery"')
    expect(searchSource).toContain('const trimmedQuery = computed(() => query.value.trim())')
    expect(searchSource).toContain('const hasQuery = computed(() => !!trimmedQuery.value)')
    expect(searchSource).not.toContain('输入关键词查找当前会话消息')
    expect(searchSource).toContain('role="status"')
    expect(searchSource).toContain('aria-live="polite"')
    expect(searchSource).toContain('查找聊天记录...')
    expect(searchSource).toContain("query ? '清空搜索' : '关闭查找聊天记录'")
    expect(searchSource).toContain("query ? clearQuery() : emit('close')")
    expect(searchSource).toContain('@keydown.esc.prevent="emit(\'close\')"')
    expect(searchSource).toContain('inputElement.value?.focus()')
    expect(searchSource).toContain("}, { immediate: true })")
    expect(source).toContain('ref="searchShellRef"')
    expect(source).toContain('handleSearchOutsidePointerDown')
    expect(source).toContain('searchShellRef.value?.contains(target)')
    expect(source).toContain("document.addEventListener('pointerdown', handleSearchOutsidePointerDown)")
    expect(source).toContain("document.removeEventListener('pointerdown', handleSearchOutsidePointerDown)")
    expect(source).toContain('void closeSearch(true)')
    expect(searchSource).toContain('}, 250)')
    expect(source).toContain(':participants="model.messageList.participants"')
    expect(searchSource).toContain("import WebqqAvatar from './webqq-avatar.vue'")
    expect(searchSource).toContain('<WebqqAvatar')
    expect(searchSource).toContain('participant(hit.authorId).isBot')
    expect(searchSource).toContain('participant(hit.authorId).avatar')
    expect(searchSource).toContain('participant(hit.authorId).name')
    expect(searchSource).toContain('formatSearchTime(hit.createdAt)')
    expect(searchSource).toContain('formatSummary(hit.summary)')
    const chatRule = styles.slice(styles.indexOf('.webqq-chat {')).split('}')[0]
    expect(chatRule).toContain('grid-template-rows: auto minmax(0, 1fr)')
    const searchShellRule = styles.slice(styles.indexOf('.webqq-chat-search-shell {')).split('}')[0]
    expect(searchShellRule).toContain('width: 36px')
    expect(styles).toContain('.webqq-chat-search-shell.is-expanded')
    const resultsRule = styles.slice(styles.indexOf('.webqq-message-search-results {')).split('}')[0]
    expect(resultsRule).toContain('position: absolute')
    expect(resultsRule).toContain('width: 100%')
    expect(resultsRule).toContain('max-width: 100%')
    expect(resultsRule).toContain('z-index:')
    const triggerRule = styles.slice(styles.indexOf('.webqq-chat-search-trigger {')).split('}')[0]
    expect(triggerRule).toContain('color: var(--webqq-accent)')
    const fieldIconRule = styles.slice(styles.indexOf('.webqq-message-search-field > svg {')).split('}')[0]
    expect(fieldIconRule).toContain('var(--webqq-accent)')
    const hitRule = styles.slice(styles.indexOf('.webqq-message-search-hit {')).split('}')[0]
    expect(hitRule).toContain('grid-template-columns: 32px minmax(0, 1fr)')
    const avatarRule = styles.slice(styles.indexOf('.webqq-message-search-avatar {')).split('}')[0]
    expect(avatarRule).toContain('--webqq-avatar-size: 32px')
    expect(styles).toContain('.webqq-chat-header-actions')
    expect(styles).not.toContain('cursor:')
    expect(pageSource).toContain('@search-conversation-messages="searchConversationMessages"')
    expect(shellSource).toContain('async function searchConversationMessages')
    expect(shellSource).toContain('workspaceController.searchConversationMessages(input)')
    expect(messageListSource).toContain('highlightMessageElement')
    expect(messageListSource).toContain('defineExpose({')
    expect(messageListSource).toContain('revealMessage,')
  })
})
