import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WebQQ 预设工作台源码契约', () => {
  it('接入独立导航、CRUD、CodeMirror 表达式装饰和跨页证据意图', () => {
    const page = readFileSync(resolve('client/page.vue'), 'utf8')
    const sidebar = readFileSync(resolve('client/webqq-sidebar.vue'), 'utf8')
    const workspace = readFileSync(resolve('client/preset-workspace.vue'), 'utf8')
    const editor = readFileSync(resolve('client/preset-source-editor.vue'), 'utf8')
    const sourceExpressions = readFileSync(resolve('client/webqq/preset-source-expressions.ts'), 'utf8')
    const modelRequests = readFileSync(resolve('client/model-request-workspace.vue'), 'utf8')
    const trajectory = readFileSync(resolve('client/model-request-trajectory.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-presets.css'), 'utf8')

    expect(sidebar).toMatch(/label:\s*['"]预设['"]/) 
    expect(sidebar).toContain('IconFileCode')
    expect(page).toContain("currentView === 'presets'")
    expect(page).toContain('<PresetWorkspace')
    expect(page).toContain(':navigation-intent="presetEvidenceIntent"')
    expect(workspace).toContain("kind === 'core' ? 'ChatLuna' : 'Character'")
    expect(workspace).toContain('ChatLuna 预设')
    expect(workspace).toContain('Character')
    expect(workspace).toContain('新建预设')
    expect(workspace).toContain('重命名预设')
    expect(workspace).toContain('删除预设')
    expect(workspace).toContain('放弃未保存修改？')
    expect(workspace).toContain("requestDirtyAction('delete')")
    expect(workspace).toContain("emit('navigateEvidence', result)")
    expect(workspace).not.toContain('打开模型请求证据')
    expect(workspace).toContain('预设已被其他位置修改')
    expect(workspace).toContain('v-if="showSaveStatus"')
    expect(workspace).not.toContain("return dirty.value ? '有未保存修改' : '已保存'")
    expect(workspace).not.toContain('webqq-preset-context-bar')
    expect(workspace).not.toContain('选择证据定位机器人')
    expect(workspace).toContain('<SelectGroup>')
    expect(workspace).not.toContain('parseDocument')
    expect(workspace).not.toContain('YAML.parse')
    expect(workspace).toContain(':kind="document.kind"')
    expect(editor).toContain("from '@codemirror/lang-yaml'")
    expect(editor).toContain('HighlightStyle.define')
    expect(editor).toContain('syntaxHighlighting(presetHighlightStyle)')
    expect(editor).toContain('EditorView.theme')
    expect(editor).toContain('Decoration.mark')
    expect(editor).toContain("source[sourceFrom] !== '{' || source[sourceTo - 1] !== '}'")
    expect(editor).toContain('codeMirrorOffset(source, sourceFrom)')
    expect(editor).toContain("expression.kind === 'control'")
    expect(editor).toContain('expression.clickable && expression.stableId')
    expect(editor).toContain('resolvePresetSourceExpressions')
    expect(editor).not.toContain('? expressionDecorations(props.expressions)')
    expect(editor).toContain("isUserEvent('input')")
    expect(editor).toContain('syncDocument.of(true)')
    expect(editor).toContain('setDecorations.of(expressionDecorations(value, activeExpressions))')
    expect(editor).toContain("emit('update:modelValue'")
    expect(sourceExpressions).toContain("from '../../src/presets/source-document'")
    expect(sourceExpressions).toContain('parsePresetSourceDocument(input.kind, input.source)')
    expect(sourceExpressions).toContain('if (input.source === input.loadedSource) return input.serverExpressions')
    expect(sourceExpressions).toContain('clickable: false')
    expect(modelRequests).toContain('navigationIntent?: PresetEvidenceNavigationIntent')
    expect(modelRequests).toContain("bodyView.value = 'analysis'")
    expect(modelRequests).toContain("mode: 'request'")
    expect(modelRequests).toContain("@locate-result=\"completeNavigationIntent\"")
    expect(modelRequests).toContain('navigationIntentFailure')
    expect(trajectory).toContain('const analysisLocateRequest = computed(() => props.externalLocate ?? internalAnalysisLocateRequest.value)')
    expect(trajectory).toContain('externalLocate?: LocateRequest')
    expect(styles).toContain('.webqq-preset-expression.is-control')
    expect(styles).toContain('.webqq-preset-expression.is-value')
    expect(styles).toContain('padding: 24px')
    expect(styles).toContain('grid-template-columns: minmax(280px, 360px) minmax(0, 1fr)')
    expect(styles).toContain('border-radius: 16px')
    expect(styles).toContain('.webqq-preset-token-key')
    expect(styles).toContain('.webqq-workspace[data-color-mode="dark"] .webqq-preset-source-editor')
  })
})
