import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WebQQ MCP 调用工作台', () => {
  it('从最左侧导航进入独立视图，并提供筛选、详情和清理控件', () => {
    const pageSource = readFileSync(resolve('client/page.vue'), 'utf8')
    const sidebarSource = readFileSync(resolve('client/webqq-sidebar.vue'), 'utf8')
    const shellSource = readFileSync(resolve('client/webqq/workspace-shell.ts'), 'utf8')
    const workspaceSource = readFileSync(resolve('client/mcp-call-workspace.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-mcp-calls.css'), 'utf8')

    expect(sidebarSource).toMatch(/label:\s*['"]MCP 调用['"]/)
    expect(sidebarSource).toContain('IconHistory')
    expect(sidebarSource).toContain("id === 'messages' || id === 'model-requests' || id === 'presets' || id === 'spaces'")
    expect(sidebarSource).not.toContain("id === 'mcp-calls'")
    expect(sidebarSource.indexOf("label: '调试'")).toBeLessThan(sidebarSource.indexOf("label: 'MCP 调用'"))
    expect(sidebarSource.indexOf("label: 'MCP 调用'")).toBeLessThan(sidebarSource.indexOf("label: '模型请求'"))
    expect(pageSource).toContain("currentView === 'mcp-calls'")
    expect(pageSource).toContain('<McpCallWorkspace')
    expect(pageSource).toContain('@query="loadMcpCallRecords"')
    expect(pageSource).toContain('@open="loadMcpCallRecord"')
    expect(pageSource).toContain('@clear="clearMcpCallRecords"')
    expect(pageSource).toContain(':visit-key="mcpCallVisitKey"')
    expect(shellSource).toContain("if (view === 'mcp-calls') mcpCallVisitKey.value += 1")
    expect(shellSource).toContain("if (currentView.value === 'mcp-calls') mcpCallVisitKey.value += 1")
    expect(shellSource).not.toContain("if (view === 'mcp-calls') void loadMcpCallRecords()")
    expect(workspaceSource).toContain('自动刷新')
    expect(workspaceSource).not.toContain('实时刷新')
    expect(workspaceSource).toContain("from './components/ui/switch'")
    expect(workspaceSource).toContain('createModelRequestLiveRefresh')
    expect(workspaceSource).toContain("liveRefresh = ref(false)")
    expect(workspaceSource).toContain('createModelRequestEnterRefresh')
    expect(workspaceSource).toContain('onActivated')
    expect(workspaceSource).toContain('enterRefresh.schedule()')
    expect(workspaceSource).toContain('visibilitychange')
    expect(workspaceSource).toContain("from './components/ui/input'")
    expect(workspaceSource).toContain("from './components/ui/checkbox'")
    expect(workspaceSource).toContain("from './components/ui/button'")
    expect(workspaceSource).toContain("from './components/ui/popover'")
    expect(workspaceSource).toContain('清理调用记录')
    expect(workspaceSource).toMatch(/variant="destructive"[^>]*>\s*<IconTrash/s)
    expect(workspaceSource).toContain('查看外部测试控制器的工具调用')
    expect(workspaceSource).toContain('选择一条记录查看参数和结果')
    expect(workspaceSource).toContain('detail.arguments')
    expect(workspaceSource).toContain('detail.result')
    expect(workspaceSource).toContain('detail.error')
    expect(workspaceSource).toContain('webqq-mcp-call-item-copy')
    expect(workspaceSource).toContain('webqq-mcp-call-timing')
    expect(workspaceSource).toContain('webqq-mcp-call-meta-list')
    expect(workspaceSource).toContain('IconCalendarTime')
    expect(workspaceSource).toContain('IconClock')
    expect(workspaceSource).toContain('item.credentialName')
    expect(workspaceSource).not.toContain('formatSource')
    expect(workspaceSource.match(/v-for="item in orderedRecords"[\s\S]*?<\/button>/)?.[0] ?? '').not.toContain('item.spaceId')
    expect(workspaceSource.match(/v-for="item in orderedRecords"[\s\S]*?<\/button>/)?.[0] ?? '').not.toContain('item.sourceIp')
    expect(workspaceSource.match(/v-for="item in orderedRecords"[\s\S]*?<\/button>/)?.[0] ?? '').not.toContain('item.errorCode')
    expect(styles).toMatch(/\.webqq-mcp-call-meta\s*\{[^}]*align-items:\s*center/s)
    expect(workspaceSource).not.toContain("emit('replay'")
    expect(workspaceSource).toMatch(/webqq-mcp-call-list-pane[\s\S]*webqq-mcp-call-list-toolbar[\s\S]*webqq-mcp-call-list/)
    expect(workspaceSource).toContain('筛选 MCP 调用')
    expect(workspaceSource).toContain('调用列表')
    expect(workspaceSource).toContain('按时间倒序')
    expect(workspaceSource).toContain('按时间正序')
    expect(workspaceSource).toContain("sortOrder = ref<'asc' | 'desc'>('desc')")
    expect(workspaceSource).toContain('toggleSortOrder')
    expect(workspaceSource).toContain('orderedRecords')
    expect(workspaceSource).toContain('orderRecordsByTime')
    expect(workspaceSource).toMatch(/function toggleSortOrder\(\) \{[\s\S]*applyFilters\(\)/)
    expect(workspaceSource).toContain('v-for="item in orderedRecords"')
    expect(workspaceSource).not.toContain('sortOpen')
    expect(workspaceSource).not.toContain('webqq-mcp-call-sort-popover')
    expect(workspaceSource).toContain('重置')
    expect(workspaceSource).not.toContain('webqq-mcp-call-filters')
    expect(workspaceSource.indexOf('webqq-mcp-call-list-toolbar')).toBeGreaterThan(workspaceSource.indexOf('webqq-mcp-call-list-pane'))
    expect(workspaceSource.indexOf('webqq-mcp-call-filter-popover')).toBeGreaterThan(workspaceSource.indexOf('webqq-mcp-call-list-toolbar'))
    expect(styles).toMatch(/\.webqq-mcp-call-workspace\s*\{[^}]*grid-template-rows:\s*auto auto minmax\(0, 1fr\)/s)
    expect(styles).toMatch(/\.webqq-mcp-call-list-toolbar\s*\{[^}]*justify-content:\s*space-between/s)
    expect(styles).toMatch(/\.webqq-mcp-call-list-toolbar\s*\{[^}]*border-bottom:\s*1px solid var\(--webqq-border\)/s)
    expect(styles).toMatch(/\.webqq-mcp-call-split\s*\{[^}]*grid-row:\s*3/s)
  })
})
