import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('WebQQ OneBot 调试工作台', () => {
  it('从最左侧导航进入独立视图，并提供筛选、详情和清理控件', () => {
    const pageSource = readFileSync(resolve('client/page.vue'), 'utf8')
    const sidebarSource = readFileSync(resolve('client/webqq-sidebar.vue'), 'utf8')
    const shellSource = readFileSync(resolve('client/webqq/workspace-shell.ts'), 'utf8')
    const debugSource = readFileSync(resolve('client/onebot-debug-workspace.vue'), 'utf8')
    const styles = readFileSync(resolve('client/styles/webqq-debug.css'), 'utf8')

    expect(sidebarSource).toMatch(/label:\s*['"]OneBot 调试['"]/)
    expect(sidebarSource).toContain('IconBug')
    expect(pageSource).toContain("currentView === 'debug'")
    expect(pageSource).toContain('<OneBotDebugWorkspace')
    expect(pageSource).toContain('const debugBots = botDirectory')
    expect(pageSource).toContain('@query="loadOneBotDebugRecords"')
    expect(pageSource).toContain('@open="loadOneBotDebugRecord"')
    expect(pageSource).toContain('@clear="clearOneBotDebugRecords"')
    expect(pageSource).toContain(':visit-key="debugVisitKey"')
    expect(shellSource).toContain("if (view === 'debug') debugVisitKey.value += 1")
    expect(shellSource).toContain("if (currentView.value === 'debug') debugVisitKey.value += 1")
    expect(shellSource).not.toContain("if (view === 'debug') void loadOneBotDebugRecords()")
    expect(debugSource).toContain('自动刷新')
    expect(debugSource).not.toContain('实时刷新')
    expect(debugSource).toContain("from '#client/components/ui/switch'")
    expect(debugSource).toContain('createModelRequestLiveRefresh')
    expect(debugSource).toContain("liveRefresh = ref(false)")
    expect(debugSource).toContain('createModelRequestEnterRefresh')
    expect(debugSource).toContain('onActivated')
    expect(debugSource).toContain('enterRefresh.schedule()')
    expect(debugSource).toContain('visibilitychange')
    expect(debugSource).toContain("from '#client/components/ui/select'")
    expect(debugSource).toContain("from '#client/components/ui/checkbox'")
    expect(debugSource).toContain("from '#client/components/ui/button'")
    expect(debugSource).toContain("from '#client/components/ui/popover'")
    expect(debugSource).toContain('清理调试记录')
    expect(debugSource).toMatch(/variant="destructive"[^>]*>\s*<IconTrash/s)
    expect(debugSource).toContain("detail.direction === 'action' ? '输入' : '事件数据'")
    expect(debugSource).toContain("detail.direction === 'action' ? '输出' : '处理结果'")
    expect(debugSource).toContain('查看最近的 action、原始事件和错误')
    expect(debugSource).toContain('选择一条记录查看输入和输出')
    expect(debugSource).not.toContain('不能重放')
    expect(debugSource).not.toContain('仅保存在内存中')
    expect(debugSource).toContain('record.source.name')
    expect(debugSource).toContain('getRecordKey(record)')
    expect(debugSource).toContain('SandboxDirectoryBot')
    expect(debugSource).toContain("import WebqqAvatar from './webqq-avatar.vue'")
    expect(debugSource).toContain('class="webqq-debug-bot-avatar"')
    expect(debugSource).toContain(':avatar="bot.avatar"')
    expect(debugSource).not.toContain('show-bot-badge')
    expect(debugSource).toContain('countLargeValueSummaries')
    expect(debugSource).toContain('已折叠')
    expect(debugSource).toContain('includeLargeValues: true')
    expect(debugSource).toContain('webqq-debug-item-copy')
    expect(debugSource).toContain('webqq-debug-timing')
    expect(debugSource).toContain('webqq-debug-meta-list')
    expect(debugSource).toContain('IconCalendarTime')
    expect(debugSource).toContain('IconClock')
    expect(debugSource).not.toContain("emit('replay'")
    expect(debugSource).toMatch(/webqq-debug-list-pane[\s\S]*webqq-debug-list-toolbar[\s\S]*webqq-debug-list/)
    expect(debugSource).toContain('筛选调试记录')
    expect(debugSource).toContain('调用列表')
    expect(debugSource).toContain('按时间倒序')
    expect(debugSource).toContain('按时间正序')
    expect(debugSource).toContain("sortOrder = ref<'asc' | 'desc'>('desc')")
    expect(debugSource).toContain('toggleSortOrder')
    expect(debugSource).toContain('orderedRecords')
    expect(debugSource).toContain('orderRecordsByTime')
    expect(debugSource).toMatch(/function toggleSortOrder\(\) \{[\s\S]*applyFilters\(\)/)
    expect(debugSource).toContain('v-for="record in orderedRecords"')
    expect(debugSource).not.toContain('sortOpen')
    expect(debugSource).not.toContain('webqq-debug-sort-popover')
    expect(debugSource).toContain('重置')
    expect(debugSource).not.toContain('webqq-debug-filters')
    expect(debugSource.indexOf('webqq-debug-list-toolbar')).toBeGreaterThan(debugSource.indexOf('webqq-debug-list-pane'))
    expect(debugSource.indexOf('webqq-debug-filter-popover')).toBeGreaterThan(debugSource.indexOf('webqq-debug-list-toolbar'))
    expect(styles).toMatch(/\.webqq-debug-workspace\s*\{[^}]*grid-template-rows:\s*auto auto minmax\(0, 1fr\)/s)
    expect(styles).toMatch(/\.webqq-debug-list-toolbar\s*\{[^}]*justify-content:\s*space-between/s)
    expect(styles).toMatch(/\.webqq-debug-list-toolbar\s*\{[^}]*border-bottom:\s*1px solid var\(--webqq-border\)/s)
    expect(styles).toMatch(/\.webqq-debug-split\s*\{[^}]*grid-row:\s*3/s)
    expect(styles).toMatch(/\.webqq-debug-meta\s*\{[^}]*align-items:\s*center/s)
    expect(styles).toMatch(/\.webqq-debug-list-pane,\s*\n\s*\.webqq-debug-detail-pane\s*\{[^}]*display:\s*grid/s)
    expect(styles).toMatch(/\.webqq-debug-empty,\s*\n\s*\.webqq-debug-error\s*\{[^}]*place-items:\s*center/s)
  })

  it('会话观察按两个方向各自成句，不复用一条只讲偏离的文案', () => {
    const debugSource = readFileSync(resolve('client/onebot-debug-workspace.vue'), 'utf8')

    expect(debugSource).toContain('aria-label="会话观察"')
    expect(debugSource).toContain("'reply-left-event-conversation'")
    expect(debugSource).toContain('回复偏离了事件来源会话')
    expect(debugSource).toContain('沙盒不替插件把回复归位到会话实例')
    expect(debugSource).toContain("'history-followed-event-conversation'")
    expect(debugSource).toContain('历史查询跟随了事件来源会话')
    expect(debugSource).toContain('避免另一条对话线的历史静默变成模型输入')
    expect(debugSource).toContain('conversationObservationCopy')
    // 读取方向的实际会话就是来源实例，「实际落点」这种只对写入成立的说法不能留在共用文案里。
    expect(debugSource).toContain('实际会话')
    expect(debugSource).not.toContain('实际落点')
    expect(debugSource).not.toContain('detail.drift')
  })

  it('使用独立网格和统一控件基线，避免筛选器溢出与黑色描边', () => {
    const debugSource = readFileSync(resolve('client/onebot-debug-workspace.vue'), 'utf8')
    const modelRequestSource = readFileSync(resolve('client/model-request-workspace.vue'), 'utf8')
    const debugStyles = readFileSync(resolve('client/styles/webqq-debug.css'), 'utf8')
    const primitives = readFileSync(resolve('client/styles/webqq-primitives.css'), 'utf8')

    expect(debugSource).toContain('webqq-debug-control')
    expect(debugStyles).toMatch(/\.webqq-debug-bot-avatar\s*\{[^}]*border-radius:\s*50%/s)
    expect(debugStyles).toMatch(/\.webqq-debug-workspace\s*\{[^}]*grid-template-rows:\s*auto auto minmax\(0, 1fr\)/s)
    expect(debugStyles).toMatch(/\.webqq-debug-list\s*\{[^}]*height:\s*100%/s)
    // 控件颜色统一由 shadcn 控件基线接管：devMode 缺失按需工具类时也不会退化成黑描边或无底色。
    expect(primitives).toContain('[data-slot="select-trigger"]')
    expect(primitives).toMatch(/\[data-variant="destructive"\][^}]*\{[^}]*background:\s*#dc2626/s)
    // Reka 的 as-child 会把 Button 的 data-slot 覆盖成 popover-trigger；基线必须覆盖最终 DOM 属性。
    expect(modelRequestSource).toMatch(/<PopoverTrigger as-child>[\s\S]*?<Button[\s\S]*?variant="outline"/)
    expect(debugSource).toMatch(/<PopoverTrigger as-child>[\s\S]*?<Button[\s\S]*?variant="outline"/)
    expect(primitives).toMatch(/\[data-slot="popover-trigger"\][^}]*\[data-variant="outline"\]/)
  })
})
